image: golang:1.15

stages:
  - build
  - test

compile:
  stage: build
  script:
    - go build

test:
  stage: test
  before_script:
    - go get github.com/t-yuki/gocover-cobertura
  script:
    - go test -cover -coverprofile=coverage.txt
    - gocover-cobertura < coverage.txt > cobertura-coverage.xml
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    reports:
      cobertura: cobertura-coverage.xml
